USE ADBMS;

CREATE TABLE EMPLOYEE(
EMPLOYEE_NO INT PRIMARY KEY,
EMPLOYEE_NAME VARCHAR(25) NOT NULL,
TITLE VARCHAR(25) NOT NULL,
DEPARTMENT_NO INT NOT NULL
);


CREATE TABLE SITE(
SITE_NAME VARCHAR(10) NOT NULL,
EMP_FRAGMENT VARCHAR(10) NOT NULL,
PRIMARY KEY(SITE_NAME, EMP_FRAGMENT)
);


INSERT INTO EMPLOYEE VALUES
(1, "AMAAN KHAN", "SOFTWARE DEVELOPER", 5),
(2, "JASRAJ SINGH BATTH", "SOFTWARE DEVELOPER", 9),
(3, "JAGJYOT SINGH GRANTHI", "DEVOPS DEVELOPER", 12),
(4, "ATHARV SHINDE", "MANAGER OF FINANCE", 25),
(5, "VIRAT KOHLI", "MANAGER OF ADS", 27),
(6, "MS DHONI", "SPECIAL OPS", 17),
(7, "SACHIN TENDULKAR", "GREATEST DEVELOPER", 17)
;

SELECT * FROM EMPLOYEE;


-- CREATE A HORIZONTAL FRAGMENTATIONS
-- FOR EMPLOYEE1
CREATE TABLE EMPLOYEE1 AS (SELECT * FROM EMPLOYEE WHERE DEPARTMENT_NO >= 1 AND DEPARTMENT_NO <= 10);
SELECT * FROM EMPLOYEE1;

-- FOR EMPLOYEE2
CREATE TABLE EMPLOYEE2 AS (SELECT * FROM EMPLOYEE WHERE DEPARTMENT_NO >= 11 AND DEPARTMENT_NO <= 20);
SELECT * FROM EMPLOYEE2;

-- FOR EMPLOYEE3
CREATE TABLE EMPLOYEE3 AS (SELECT * FROM EMPLOYEE WHERE DEPARTMENT_NO >= 21 AND DEPARTMENT_NO <= 30);
SELECT * FROM EMPLOYEE3;


INSERT INTO SITE VALUES
("SITE 1", "EMPLOYEE1"),
("SITE 2", "EMPLOYEE2"),
("SITE 3", "EMPLOYEE2"),
("SITE 3", "EMPLOYEE3"),
("SITE 4", "EMPLOYEE1");

SELECT * FROM SITE;


-- QUERIES
-- 1. QUERY TO FIND TITLES OF ALL THE EMPLOYEES
SELECT EMPLOYEE_NAME, TITLE FROM EMPLOYEE1
UNION
SELECT EMPLOYEE_NAME, TITLE FROM EMPLOYEE2
UNION
SELECT EMPLOYEE_NAME, TITLE FROM EMPLOYEE3;


-- 2. QUERY TO FIND NUMBER OF DEVELOPERS WHOSE DEPARTMENT_NO IS BETWEEN (1,10)
SELECT COUNT(*) AS NO_OF_DEVELOPERS FROM EMPLOYEE1 WHERE TITLE LIKE "%DEVELOPER";


-- 3. QUERY TO FIND ALL THE MANAGERS WHOSE DEPARTMENT_NO IS BETWEEN (21, 30)
SELECT EMPLOYEE_NAME AS NAME, TITLE FROM EMPLOYEE3 WHERE TITLE LIKE "MANAGER%";


-- 4. QUERY TO FIND ALL THE DEVELOPERS
SELECT EMPLOYEE_NAME, TITLE FROM EMPLOYEE1 WHERE TITLE LIKE "%DEVELOPER"
UNION
SELECT EMPLOYEE_NAME, TITLE FROM EMPLOYEE2 WHERE TITLE LIKE "%DEVELOPER"
UNION
SELECT EMPLOYEE_NAME, TITLE FROM EMPLOYEE3 WHERE TITLE LIKE "%DEVELOPER";

-- 5. CHANGE TITLE OF ALL EMPLOYEES OF DEPARTMENT 17 TO CEOS
UPDATE EMPLOYEE2 SET TITLE = "CEO" WHERE DEPARTMENT_NO = 17;
SELECT * FROM EMPLOYEE2;